title: E-TKT
description: Anachronic label maker

remote_theme: just-the-docs/just-the-docs@v0.4.0.rc2

logo: "/assets/logo.png"




# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2022 Andrei Speridião. Distributed by an <a href=\"https://github.com/andreisperid/E-TKT/blob/main/LICENSE">MIT license.</a>\"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

color_scheme: dark
